<?php $presets["skin06s"] = array (
  'preset' => 'skin06s',
  'header-logo_regular' => 
  array (
    0 => '/inc/presets/images/full/skin06s.header-logo-regular.png?w=42&h=61',
    1 => 0,
  ),
  'header-logo_hd' => 
  array (
    0 => '/inc/presets/images/full/skin06s.header-logo-hd.png?w=84&h=122',
    1 => 0,
  ),
  'bottom_bar-logo_regular' => 
  array (
    0 => '/inc/presets/images/full/skin06s.bottom-bar-logo-regular.png?w=24&h=39',
    1 => 0,
  ),
  'bottom_bar-logo_hd' => 
  array (
    0 => '/inc/presets/images/full/skin06s.bottom-bar-logo-hd.png?w=48&h=78',
    1 => 0,
  ),
  'general-floating_menu_show_logo' => '1',
  'general-floating_menu_logo_regular' => 
  array (
    0 => '/inc/presets/images/full/skin06s.general-floating-menu-logo-regular.png?w=24&h=39',
    1 => 0,
  ),
  'general-floating_menu_logo_hd' => 
  array (
    0 => '/inc/presets/images/full/skin06s.general-floating-menu-logo-hd.png?w=48&h=78',
    1 => 0,
  ),
  'general-bg_color' => '#ffffff',
  'general-bg_opacity' => 100,
  'general-bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'top',
  ),
  'general-bg_fullscreen' => false,
  'general-content_width' => '1250px',
  'general-layout' => 'boxed',
  'general-box_width' => '1280px',
  'general-boxed_bg_color' => '#ffffff',
  'general-boxed_bg_image' => 
  array (
    'image' => '/inc/presets/images/full/skin06s.general-boxed-bg-image.jpg',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'center',
  ),
  'general-boxed_bg_fullscreen' => '1',
  'general-show_titles' => '1',
  'general-title_align' => 'center',
  'general-show_breadcrumbs' => '0',
  'general-responsive' => '1',
  'general-accent_bg_color' => '#5fd45c',
  'general-border_radius' => 3,
  'general-show_rel_posts' => '1',
  'general-rel_posts_head_title' => 'Related posts',
  'general-rel_posts_max' => 6,
  'general-smooth_scroll' => 'off',
  'fonts-font_family' => 'Open Sans',
  'fonts-normal_size' => 13,
  'fonts-normal_size_line_height' => 22,
  'fonts-small_size' => 12,
  'fonts-small_size_line_height' => 21,
  'fonts-big_size' => 14,
  'fonts-big_size_line_height' => 24,
  'fonts-h1_font_family' => 'Roboto',
  'fonts-h1_font_size' => 47,
  'fonts-h1_line_height' => 53,
  'fonts-h1_uppercase' => false,
  'fonts-h2_font_family' => 'Roboto',
  'fonts-h2_font_size' => 37,
  'fonts-h2_line_height' => 43,
  'fonts-h2_uppercase' => false,
  'fonts-h3_font_family' => 'Roboto',
  'fonts-h3_font_size' => 25,
  'fonts-h3_line_height' => 31,
  'fonts-h3_uppercase' => false,
  'fonts-h4_font_family' => 'Roboto',
  'fonts-h4_font_size' => 19,
  'fonts-h4_line_height' => 25,
  'fonts-h4_uppercase' => false,
  'fonts-h5_font_family' => 'Roboto',
  'fonts-h5_font_size' => 16,
  'fonts-h5_line_height' => 23,
  'fonts-h5_uppercase' => false,
  'fonts-h6_font_family' => 'Roboto',
  'fonts-h6_font_size' => 14,
  'fonts-h6_line_height' => 23,
  'fonts-h6_uppercase' => false,
  'buttons-s_font_family' => 'Roboto',
  'buttons-s_font_size' => 12,
  'buttons-s_uppercase' => false,
  'buttons-s_line_height' => 26,
  'buttons-m_font_family' => 'Roboto',
  'buttons-m_font_size' => 15,
  'buttons-m_uppercase' => false,
  'buttons-m_line_height' => 38,
  'buttons-l_font_family' => 'Roboto',
  'buttons-l_font_size' => 17,
  'buttons-l_uppercase' => false,
  'buttons-l_line_height' => 46,
  'top_bar-bg_color' => '#2684b4',
  'top_bar-bg_opacity' => 100,
  'top_bar-bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'center',
  ),
  'top_bar-text_color' => '#ffffff',
  'header-bg_color' => '#006fa8',
  'header-bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'top',
  ),
  'header-transparent_bg_color' => '#ffffff',
  'header-transparent_bg_opacity' => 100,
  'header-bg_height' => 76,
  'header-layout' => 'side',
  'header-show_floating_menu' => '1',
  'content-headers_color' => '#3a3a3a',
  'content-primary_text_color' => '#888888',
  'stripes-stripe_1_color' => '#fafafa',
  'stripes-stripe_1_bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'center',
  ),
  'stripes-stripe_1_headers_color' => '#3a3a3a',
  'stripes-stripe_1_text_color' => '#888888',
  'stripes-stripe_2_color' => '#006fa8',
  'stripes-stripe_2_bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'center',
  ),
  'stripes-stripe_2_headers_color' => '#ffffff',
  'stripes-stripe_2_text_color' => '#ffffff',
  'stripes-stripe_3_color' => '#f8f8f8',
  'stripes-stripe_3_bg_image' => 
  array (
    'image' => '/inc/presets/images/full/skin06r.stripes-stripe-3-bg-image.jpg',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'center',
  ),
  'stripes-stripe_3_headers_color' => '#3a3a3a',
  'stripes-stripe_3_text_color' => '#888888',
  'sidebar-bg_color' => '#f9f9f9',
  'sidebar-bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'center',
  ),
  'sidebar-headers_color' => '#3a3a3a',
  'sidebar-primary_text_color' => '#888888',
  'footer-bg_color' => '#006fa8',
  'footer-bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'top',
  ),
  'footer-headers_color' => '#3a3a3a',
  'footer-primary_text_color' => '#888888',
  'bottom_bar-bg_color' => '#ffffff',
  'bottom_bar-bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'top',
  ),
  'bottom_bar-color' => '#bfbfbf',
  'bottom_bar-credits' => '1',
  'top_bar-font_size' => 'normal',
  'top_bar-bg_mode' => 'disabled',
  'menu-font_family' => 'Roboto',
  'menu-font_size' => 16,
  'menu-font_uppercase' => '1',
  'menu-next_level_indicator' => false,
  'menu-font_color' => '#ffffff',
  'menu-hover_font_color_mode' => 'color',
  'menu-hover_font_color' => '#ffffff',
  'menu-hover_font_color_gradient' => 
  array (
    0 => '#dd3333',
    1 => '#0ce6ab',
  ),
  'menu-decoration_style' => 'brackets',
  'menu-hover_decoration_color_mode' => 'accent',
  'menu-hover_decoration_color' => '#a7e673',
  'menu-hover_decoration_color_gradient' => 
  array (
    0 => '#eeee22',
    1 => '#0bed56',
  ),
  'top_bar-paddings' => 10,
  'menu-iconfont_size' => 14,
  'menu-items_distance' => 26,
  'submenu-font_family' => 'Open Sans',
  'submenu-font_size' => 13,
  'submenu-font_uppercase' => '1',
  'submenu-next_level_indicator' => false,
  'submenu-font_color' => '#89ccf3',
  'submenu-hover_font_color_mode' => 'accent',
  'submenu-hover_font_color' => '#895cb8',
  'submenu-hover_font_color_gradient' => 
  array (
    0 => '#81d742',
    1 => '#eeee22',
  ),
  'submenu-iconfont_size' => 12,
  'submenu-items_distance' => 9,
  'submenu-bg_color' => '#005b89',
  'submenu-bg_opacity' => 97,
  'submenu-bg_width' => 230,
  'general-accent_color_mode' => 'color',
  'general-accent_bg_color_gradient' => 
  array (
    0 => '#2578e9',
    1 => '#3fe7d9',
  ),
  'header-left_layout_elements' => 
  array (
    'top_bar_left' => 
    array (
      0 => 'email',
      1 => 'phone',
      2 => 'skype',
    ),
    'top_bar_right' => 
    array (
      0 => 'social_icons',
    ),
    'nav_area' => 
    array (
      0 => 'search',
    ),
  ),
  'header-center_layout_elements' => 
  array (
    'nav_area' => 
    array (
      0 => 'social_icons',
    ),
  ),
  'header-near_logo_font_size' => 'normal',
  'header-near_logo_bg_color' => '#ffffff',
  'header-classic_layout_elements' => 
  array (
    'logo_area' => 
    array (
      0 => 'phone',
      1 => 'skype',
      2 => 'email',
      3 => 'search',
      4 => 'cart',
    ),
    'nav_area' => 
    array (
      0 => 'social_icons',
    ),
  ),
  'header-side_paddings' => 0,
  'header-side_position' => 'left',
  'header-side_menu_align' => 'center',
  'header-side_layout_elements' => 
  array (
    'bottom' => 
    array (
      0 => 'phone',
      1 => 'cart',
      2 => 'social_icons',
    ),
  ),
  'header-woocommerce_cart_icon' => '1',
  'header-search_caption' => 'Search',
  'header-left_layout_fullwidth' => false,
  'header-woocommerce_cart_caption' => 'Cart',
  'header-woocommerce_counter_bg_mode' => 'color',
  'header-woocommerce_counter_bg_color' => '#489bca',
  'header-woocommerce_counter_bg_color_gradient' => 
  array (
    0 => '#dd3333',
    1 => '#81d742',
  ),
  'header-login_caption' => 'Login',
  'header-soc_icon_color' => '#ffffff',
  'header-soc_icon_hover_color' => '#ffffff',
  'header-logo_padding_top' => '50',
  'header-logo_padding_bottom' => '50',
  'float_menu-height' => 60,
  'float_menu-bg_color_mode' => 'header_color',
  'float_menu-bg_color' => '#ffffff',
  'float_menu-transparency' => 100,
  'header-side_menu_visibility' => 'always_visible',
  'header-side_menu_width' => '280px',
  'header-side_menu_lines' => '1',
  'header-side_menu_lines_color' => '#2684b4',
  'header-classic_menu_bg_mode' => 'content_line',
  'header-classic_menu_bg_color' => '#2684b4',
  'header-center_menu_bg_mode' => 'disabled',
  'header-center_menu_bg_color' => '#2684b4',
  'header-soc_icon_bg_color_mode' => 'color',
  'header-soc_icon_bg_color' => '#489bca',
  'header-soc_icon_bg_color_gradient' => 
  array (
    0 => '#8224e3',
    1 => '#43d8c7',
  ),
  'header-soc_icon_hover_bg_color_mode' => 'accent',
  'header-soc_icon_hover_bg_color' => '#ffffff',
  'header-soc_icon_hover_bg_color_gradient' => 
  array (
    0 => '#ef5689',
    1 => '#a6ff16',
  ),
  'general-title_size' => 'h1',
  'general-title_height' => 136,
  'general-title_bg_mode' => 'content_line',
  'general-title_bg_color' => '#fafafa',
  'general-breadcrumbs_color' => '#bcbcbc',
  'general-breadcrumbs_bg_color' => 'disabled',
  'general-title_bg_image' => 
  array (
    'image' => '/images/backgrounds/patterns/full/brickwall.gif',
    'repeat' => 'no-repeat',
    'position_x' => 'center',
    'position_y' => 'center',
  ),
  'general-title_bg_fullscreen' => false,
  'general-title_bg_fixed' => false,
  'general-title_bg_parallax' => '',
  'buttons-style' => 'flat',
  'buttons-color_mode' => 'accent',
  'buttons-color' => '#81d742',
  'buttons-color_gradient' => 
  array (
    0 => '#dd3333',
    1 => '#3a892a',
  ),
  'buttons-s_border_radius' => 3,
  'buttons-m_border_radius' => 3,
  'buttons-l_border_radius' => 3,
  'general-style' => 'ios7',
  'general-title_color' => '#3a3a3a',
  'image_hover-style' => 'none',
  'image_hover-default_icon' => 'white_icon',
  'image_hover-color_mode' => 'color',
  'image_hover-color' => '#006fa8',
  'image_hover-color_gradient' => 
  array (
    0 => '#000000',
    1 => '#303030',
  ),
  'image_hover-opacity' => 50,
  'image_hover-with_icons_opacity' => 94,
  'general-next_prev_in_album' => '1',
  'general-show_back_button_in_album' => '1',
  'general-album_back_button_target_page_id' => 16237,
  'general-album_meta_on' => '1',
  'general-album_meta_date' => '1',
  'general-album_meta_author' => false,
  'general-album_meta_categories' => '1',
  'general-album_meta_comments' => false,
  'general-boxed_bg_fixed' => '1',
  'sidebar-width' => 26,
  'sidebar-vertical_distance' => 60,
  'sidebar-divider-vertical' => '1',
  'sidebar-divider-horizontal' => '1',
  'header-mobile-first_switch-after' => 1100,
  'header-mobile-first_switch-logo' => 'mobile',
  'header-mobile-second_switch-after' => 400,
  'header-mobile-second_switch-logo' => 'mobile',
  'header-mobile-menu_color' => 'accent',
  'header-mobile-menu_color-background' => '#f94dda',
  'header-mobile-menu_color-text' => '#000000',
  'general-mobile_logo-regular' => 
  array (
    0 => '/inc/presets/images/full/skin06s.general-mobile-logo-regular.png?w=42&h=61',
    1 => 0,
  ),
  'general-mobile_logo-hd' => 
  array (
    0 => '/inc/presets/images/full/skin06s.general-mobile-logo-hd.png?w=84&h=122',
    1 => 0,
  ),
  'general-mobile_logo-padding_top' => '25',
  'general-mobile_logo-padding_bottom' => '25',
  'footer-style' => 'content_width_line',
  'footer-slide-out-mode' => '0',
  'footer-paddings-top-bottom' => 50,
  'footer-paddings-columns' => 22,
  'bottom_bar-style' => 'content_width_line',
  'footer-collapse_after' => 970,
  'header-background' => 'normal',
  'header-menu_text_color_mode' => 'light',
  'header-menu_hover_color_mode' => 'light',
  'header-menu_top_bar_color_mode' => 'light',
  'header-bg_opacity' => 100,
  'header-bg_fullscreen' => false,
  'header-bg_fixed' => false,
  'header-center_menu_bg_opacity' => 100,
  'header-classic_menu_bg_opacity' => 100,
  'header-side_menu_lines_opacity' => 90,
  'general-bg_fixed' => false,
  'header-style' => 'solid_background',
  'general-responsiveness-treshold' => 970,
  'header-side_menu_dropdown_style' => 'down',
  'header-decoration' => 'line',
  'header-decoration_color' => '#2684b4',
  'sidebar-visual_style' => 'with_bg',
  'header-left_layout_elements_visibility' => 'show',
  'header-center_layout_elements_visibility' => 'show',
  'header-classic_layout_elements_visibility' => 'show',
  'header-side_layout_elements_visibility' => 'show',
); ?>